name: cubierto
services:

  frontend:
    container_name: cubierto-front
    build:
      context: ./client      
    restart: always
    networks:
      - cubierto-net
    ports:
      - 5012:80

  backend:
    container_name: cubierto-back
    build:
      context: ./server
    ports:
      - 5013:5013
    restart: always
    networks:
      - cubierto-net
networks:
  cubierto-net:
    driver: bridge
